version: "3"
services:
  cyrka-mongodb:
    image: mongo
    volumes:
      - /opt/cyrka/data:/data/db
    networks:
      - cyrka-net
  cyrka-api:
    build: ./cyrka.api
    networks:
      - cyrka-net
  cyrka-nginx:
    build: ./cyrka.nginx
    ports:
     - "80:80"
    networks:
      - cyrka-net
networks:
  cyrka-net:
