#### Projects ####

### get all
GET http://localhost:5000/projects HTTP/1.1

### register
POST http://localhost:5000/projects HTTP/1.1

### set customer
POST http://localhost:5000/projects/SUBST-1802-1/customer HTTP/1.1
Content-Type: application/json

{
	"id": "8efec7a9-941f-4c20-aa36-ba41a19cecdb",
  "name": "HBO"
}

### set title
POST http://localhost:5000/projects/SUBST-1802-1/title HTTP/1.1
Content-Type: application/json

{
	"id": "edb78042-7a40-4b33-a1ac-344abfa45f83",
  "name": "Pilot season 1",
  "numberOfEpisodes": 3
}

### set episode
POST http://localhost:5000/projects/SUBST-1802-1/episode HTTP/1.1
Content-Type: application/json

{
	"number": 1,
  "duration": 55
}

#### Customers ####

### get all
GET http://localhost:5000/customers HTTP/1.1

### register
POST http://localhost:5000/customers HTTP/1.1
Content-Type: application/json

{
	"name": "HBO"
}


###
PUT http://localhost:5000/customers/202cd1bf-5c5f-4895-a45c-d316571eed08/titles/ee79f760-058f-482d-89bc-1e4229b25608
Content-Type: application/json

{
	"name": "Ну погоди СССР",
	"numberOfSeries": 15
}

#### Job Types ####

GET http://localhost:5000/jobs/types HTTP/1.1

###

GET http://localhost:5000/jobs/types/47f91b73-9f3a-4e39-a5a5-eab73c9e7340 HTTP/1.1

###

POST http://localhost:5000/jobs/types HTTP/1.1
Content-Type: application/json

{
	"name": "Subtitling",
	"unit": "minute",
	"rate": 99.99
}

###

PUT http://localhost:5000/jobs/types/47f91b73-9f3a-4e39-a5a5-eab73c9e7340 HTTP/1.1
Content-Type: application/json

{
	"name": "Subtitling",
	"description": "субтитрирование",
	"unit": "minute",
	"rate": 99.99
}
