#### Customers ####

GET http://localhost:5000/customers HTTP/1.1

###

POST http://localhost:5000/customers HTTP/1.1
Content-Type: application/json

{
	"name": "HBO"
}


###

PUT http://localhost:5000/customers/202cd1bf-5c5f-4895-a45c-d316571eed08/titles/ee79f760-058f-482d-89bc-1e4229b25608
Content-Type: application/json

{
	"name": "Ну погоди СССР",
	"numberOfSeries": 15
}

#### Job Types ####

GET http://localhost:5000/jobs/types HTTP/1.1

###

GET http://localhost:5000/jobs/types/47f91b73-9f3a-4e39-a5a5-eab73c9e7340 HTTP/1.1

###

POST http://localhost:5000/jobs/types HTTP/1.1
Content-Type: application/json

{
	"name": "Subtitling",
	"unit": "minute",
	"rate": 99.99
}

###

PUT http://localhost:5000/jobs/types/47f91b73-9f3a-4e39-a5a5-eab73c9e7340 HTTP/1.1
Content-Type: application/json

{
	"name": "Subtitling",
	"description": "субтитрирование",
	"unit": "minute",
	"rate": 99.99
}
