@token =

#### Projects ####

### get all
GET http://localhost:5000/projects HTTP/1.1
Authorization: Bearer {{token}}


### register
POST http://localhost:5000/projects HTTP/1.1
Authorization: Bearer {{token}}

### set product
POST http://localhost:5000/projects/SUBST-1805-1/product HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"customerId": "0c2ddce6-6435-49f5-b9ac-83d86b0377d3",
  "customerName": "ЦПШ",
	"titleId": "4b091822-c210-45ee-a25b-44738891bf57",
  "titleName": "Коловорот и каток",
  "totalEpisodes": 2,
	"episodeNumber": 1,
  "episodeDuration": 73
}

### set job
POST http://localhost:5000/projects/SUBST-1805-1/job HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"jobTypeId": "c42bc856-ff81-4ad1-b693-4260eebdc178",
	"jobTypeName": "Субтитрирование",
	"unitName": "Minute",
	"ratePerUnit": 350.0,
	"amount": 22
}

### change job
PUT http://localhost:5000/projects/SUBST-1805-1/jobs/c42bc856-ff81-4ad1-b693-4260eebdc178 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"ratePerUnit": 349,
	"amount": 70
}

### set status
POST http://localhost:5000/projects/SUBST-1805-1/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"status": "inprogress"
}

### set payments
POST http://localhost:5000/projects/SUBST-1805-1/payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"editorpayment": 937.10,
	"translatorpayment": 320
}

#### Customers ####

### get all
GET http://localhost:5000/customers HTTP/1.1
Authorization: Bearer {{token}}

### register
POST http://localhost:5000/customers HTTP/1.1
Content-Type: application/json

{
	"name": "HBO"
}

### register title

PUT http://localhost:5000/customers/202cd1bf-5c5f-4895-a45c-d316571eed08/titles/ee79f760-058f-482d-89bc-1e4229b25608
Content-Type: application/json

{
	"name": "Ну погоди СССР",
	"numberOfSeries": 15
}

#### Job Types ####

GET http://localhost:5000/jobs/types HTTP/1.1
Authorization: Bearer {{token}}

###

GET http://localhost:5000/jobs/types/47f91b73-9f3a-4e39-a5a5-eab73c9e7340 HTTP/1.1

###

POST http://localhost:5000/jobs/types HTTP/1.1
Content-Type: application/json

{
	"name": "Subtitling",
	"unit": "minute",
	"rate": 99.99
}

###

PUT http://localhost:5000/jobs/types/47f91b73-9f3a-4e39-a5a5-eab73c9e7340 HTTP/1.1
Content-Type: application/json

{
	"name": "Subtitling",
	"description": "субтитрирование",
	"unit": "minute",
	"rate": 99.99
}
